### ISSUE TITLE
Bandeau à retirer dans Carrière + reprendre filtre et sélection d'offre

### ISSUE THREAD

**Issue by qpelegry** [railconcept/railconcept.fr#10]
Enlever les 2 bandeaux entre le bloc de texte "Bienvenue chez Rail Concept" et "les postes à pourvoir"
Modifier la partie "postes à pourvoir", afficher directement l'offre en cours peu importe la catégorie de poste sélectionné (actuellement c'est chef de projet qui est sélectionné par défaut)

**Comment by RailConcept-Raphael-Blin** [comment]
![image](https://user-images.githubusercontent.com/61592490/175542439-d4c47b80-e2eb-470a-8fe9-cba4b996a7f4.png)
