### ISSUE TITLE
Les titres des réalisations contient des tirets "-" : champ vide ou bug

### ISSUE THREAD

**Issue by RailConcept-Raphael-Blin** [railconcept/railconcept.fr#12]
![image](https://user-images.githubusercontent.com/61592490/175543668-c60d5acb-a869-422d-a222-11653d653e73.png)

**Comment by RailConcept-Raphael-Blin** [comment]
Bug apparent quand le champ client n'est pas rempli : rajouter une valeur par défaut, ou rendre le champ obligatoire, ou retirer le tiret

**Comment by oumniaelmokretar** [comment]
Il manque le nom du "donneur d'ordre".
