### ISSUE TITLE
Use "streamlined authentication expecience" to login with netlify

### ISSUE THREAD

**Issue by RailConcept-Raphael-Blin** [railconcept/railconcept.fr#36]
They seemingly gives way to directly connect with github, aad and others
https://learn.microsoft.com/en-us/azure/static-web-apps/authentication-authorization

Connecting seems easy however we still need to adapt with netlify cms, so we'll have to adjust the api azure functions to use something like https://learn.microsoft.com/en-us/azure/static-web-apps/user-information?tabs=javascript to give the token to netlify

This would avoid some hacks with proxies or redirects that constantly gets deprecated or broken by static web app's azure functions update
It would also allow us to rely on azure for security instead of doing it ourselves with comes with several pitfalls

**Comment by oumniaelmokretar** [comment]
incompatible avec Netlify CMS
