### ISSUE TITLE
Carte non fonctionnelle dans nos réalisations + images trop grandes

### ISSUE THREAD

**Issue by qpelegry** [railconcept/railconcept.fr#9]
Où est la carte ?
Modifier le format des références : images trop grandes

**Comment by RailConcept-Raphael-Blin** [comment]
https://www.railconcept.fr/realisations

**Comment by RailConcept-Raphael-Blin** [comment]
working in https://www.railconcept.fr/nos_realisations/AMO%20schema-directeur-LDFT-occitanie/

**Comment by RailConcept-Raphael-Blin** [comment]
but it makes no sense and pointing on the wrong location

**Comment by RailConcept-Raphael-Blin** [comment]
https://www.railconcept.fr/contact/ map broken in contact too

**Comment by RailConcept-Raphael-Blin** [comment]
https://github.com/railconcept/railconcept.fr/issues/15
